CREATE VIEW gold.dim_customers AS
SELECT 
ci.CST_ID AS CUSTOMER_ID,
ci.CST_KEY AS CUSTOMER_KEY,
ci.CST_FIRSTNAME AS CUSTOMER_FIRSTNAME,
ci.CST_LASTNAME AS CUSTOMER_LASTNAME,
ci.CST_MARITALSTATUS  AS MARITAL_STATUS,
ci.CST_GNDR AS CUSTOMER_GENDER,
ca.BDATE AS CUSTOMER_BIRTHDAY,
LA.CNTRY AS CUSTOMER_LOCATION
FROM silver.crm_cust_info ci
LEFT JOIN silver.erp_cust ca
ON CI.CST_KEY=CA.CID
LEFT JOIN silver.erp_loc la
ON CI.CST_KEY=LA.CID

CREATE VIEW gold.dim_products AS 
SELECT
PN.PRD_ID as PRODUCT_ID,
PN.CAT_ID AS CATEGORY_ID,
PN.PRD_KEY AS PRODUCT_KEY,
PN.PRD_NM,
PN.PRD_COST AS PRODUCT_COST,
PN.PRD_LINE AS PRODUCT_LINE,
PN.PRD_START_DT AS PRODUCT_START_DATE,
PC.CAT AS PRODUCT_CAT,
PC.SUBCAT AS PRODUCT_SUBCATEGORY,
PC.MAINTENANCE
FROM silver.crm_prd_info pn
LEFT JOIN silver.erp_px_cat pc
ON PN.CAT_ID=PC.ID
WHERE PRD_END_DT IS NULL


CREATE VIEW gold.fact_sales AS
SELECT
SD.SLS_ORD_NUM,
PR.PRODUCT_KEY,
CU.CUSTOMER_KEY,
SD.SLS_ORDER_DT,
SD.SLS_SHIP_DT,
SD.SLS_DUE_DT,
SD.SLS_SALES,
SD.SLS_QUANTITY,
SD.SLS_PRICE
FROM silver.crm_sales_details sd
LEFT JOIN gold.dim_products pr
ON sd.sls_prd_key=pr.product_key
LEFT JOIN gold.dim_customers cu
ON sd.sls_cust_id=cu.customer_id
